<?xml version="1.0" encoding="UTF-8"?>
<testng-results retried="1" ignored="0" total="3" passed="1" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-02-05T03:30:06 IST" name="Suite" finished-at="2024-02-05T03:30:22 IST" duration-ms="16714">
    <groups>
      <group name="errorHandling">
        <method signature="ErrorValidation.WrongPasswordLogin()[pri:0, instance:LearningAutomation.SeleniumFrameworkDesign.Test.ErrorValidation@332796d3]" name="WrongPasswordLogin" class="LearningAutomation.SeleniumFrameworkDesign.Test.ErrorValidation"/>
      </group> <!-- errorHandling -->
    </groups>
    <test started-at="2024-02-05T03:30:06 IST" name="ErrorTest" finished-at="2024-02-05T03:30:17 IST" duration-ms="11265">
      <class name="LearningAutomation.SeleniumFrameworkDesign.Test.ErrorValidation">
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:LearningAutomation.SeleniumFrameworkDesign.Test.ErrorValidation@332796d3]" started-at="2024-02-05T03:30:06 IST" name="launchApplication" finished-at="2024-02-05T03:30:11 IST" duration-ms="5214" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method retried="true" signature="WrongPasswordLogin()[pri:0, instance:LearningAutomation.SeleniumFrameworkDesign.Test.ErrorValidation@332796d3]" started-at="2024-02-05T03:30:11 IST" name="WrongPasswordLogin" finished-at="2024-02-05T03:30:12 IST" duration-ms="995" status="SKIP">
          <exception class="org.junit.ComparisonFailure">
            <message>
              <![CDATA[expected:<Incorrect email [o]r password.> but was:<Incorrect email []r password.>]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.junit.ComparisonFailure: expected:<Incorrect email [o]r password.> but was:<Incorrect email []r password.>
at org.junit.Assert.assertEquals(Assert.java:117)
at org.junit.Assert.assertEquals(Assert.java:146)
at LearningAutomation.SeleniumFrameworkDesign.Test.ErrorValidation.WrongPasswordLogin(ErrorValidation.java:16)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:28)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:418)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:829)
]]>
            </full-stacktrace>
          </exception> <!-- org.junit.ComparisonFailure -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- WrongPasswordLogin -->
        <test-method is-config="true" signature="tearoff()[pri:0, instance:LearningAutomation.SeleniumFrameworkDesign.Test.ErrorValidation@332796d3]" started-at="2024-02-05T03:30:12 IST" name="tearoff" finished-at="2024-02-05T03:30:12 IST" duration-ms="359" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearoff -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:LearningAutomation.SeleniumFrameworkDesign.Test.ErrorValidation@332796d3]" started-at="2024-02-05T03:30:12 IST" name="launchApplication" finished-at="2024-02-05T03:30:16 IST" duration-ms="3291" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="WrongPasswordLogin()[pri:0, instance:LearningAutomation.SeleniumFrameworkDesign.Test.ErrorValidation@332796d3]" started-at="2024-02-05T03:30:16 IST" name="WrongPasswordLogin" finished-at="2024-02-05T03:30:16 IST" duration-ms="657" status="FAIL">
          <exception class="org.junit.ComparisonFailure">
            <message>
              <![CDATA[expected:<Incorrect email [o]r password.> but was:<Incorrect email []r password.>]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.junit.ComparisonFailure: expected:<Incorrect email [o]r password.> but was:<Incorrect email []r password.>
at org.junit.Assert.assertEquals(Assert.java:117)
at org.junit.Assert.assertEquals(Assert.java:146)
at LearningAutomation.SeleniumFrameworkDesign.Test.ErrorValidation.WrongPasswordLogin(ErrorValidation.java:16)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:28)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:418)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:829)
]]>
            </full-stacktrace>
          </exception> <!-- org.junit.ComparisonFailure -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- WrongPasswordLogin -->
        <test-method is-config="true" signature="tearoff()[pri:0, instance:LearningAutomation.SeleniumFrameworkDesign.Test.ErrorValidation@332796d3]" started-at="2024-02-05T03:30:17 IST" name="tearoff" finished-at="2024-02-05T03:30:17 IST" duration-ms="188" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearoff -->
      </class> <!-- LearningAutomation.SeleniumFrameworkDesign.Test.ErrorValidation -->
    </test> <!-- ErrorTest -->
    <test started-at="2024-02-05T03:30:06 IST" name="CorrectTest" finished-at="2024-02-05T03:30:22 IST" duration-ms="16714">
      <class name="LearningAutomation.SeleniumFrameworkDesign.Test.StandAlone">
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:LearningAutomation.SeleniumFrameworkDesign.Test.StandAlone@12d2ce03]" started-at="2024-02-05T03:30:06 IST" name="launchApplication" finished-at="2024-02-05T03:30:11 IST" duration-ms="5283" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="submitOrder()[pri:0, instance:LearningAutomation.SeleniumFrameworkDesign.Test.StandAlone@12d2ce03]" started-at="2024-02-05T03:30:11 IST" name="submitOrder" finished-at="2024-02-05T03:30:22 IST" duration-ms="11027" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- submitOrder -->
        <test-method is-config="true" signature="tearoff()[pri:0, instance:LearningAutomation.SeleniumFrameworkDesign.Test.StandAlone@12d2ce03]" started-at="2024-02-05T03:30:22 IST" name="tearoff" finished-at="2024-02-05T03:30:22 IST" duration-ms="211" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearoff -->
      </class> <!-- LearningAutomation.SeleniumFrameworkDesign.Test.StandAlone -->
    </test> <!-- CorrectTest -->
  </suite> <!-- Suite -->
</testng-results>
